/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceAvecC
 * Method:    nativeInitGame
 * Signature: (Ljava/lang/String;LJeuHex;)C
 */
JNIEXPORT jchar JNICALL Java_InterfaceAvecC_nativeInitGame
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcXCoord
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcXCoord
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcYCoord
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcYCoord
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcPosition
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcPosition
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativePlacePiece
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativePlacePiece
  (JNIEnv *, jclass, jint, jchar);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeGetSpots
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterfaceAvecC_nativeGetSpots
  (JNIEnv *, jclass, jstring);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeSaveGame
 * Signature: (Ljava/lang/String;Ljava/lang/String;[I[I)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_nativeSaveGame
  (JNIEnv *, jclass, jstring, jstring, jintArray, jintArray);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeSavePlayer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_nativeSavePlayer
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeStringToLoadPlayer
 * Signature: (CLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterfaceAvecC_nativeStringToLoadPlayer
  (JNIEnv *, jclass, jchar, jstring);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeGetSaveFile
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_InterfaceAvecC_nativeGetSaveFile
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeMiniMax
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeMiniMax
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
