/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceAvecC
 * Method:    nativeInitPiece
 * Signature: (C)LPiece;
 */
JNIEXPORT jobject JNICALL Java_InterfaceAvecC_nativeInitPiece
  (JNIEnv *, jclass, jchar);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeInitHex
 * Signature: (IIC)LHex;
 */
JNIEXPORT jobject JNICALL Java_InterfaceAvecC_nativeInitHex
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeInitBoard
 * Signature: (I)LBoard;
 */
JNIEXPORT jobject JNICALL Java_InterfaceAvecC_nativeInitBoard
  (JNIEnv *, jclass, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcXCoord
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcXCoord
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcYCoord
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcYCoord
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcPosition
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcPosition
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
