/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceAvecC
 * Method:    nativeInitPiece
 * Signature: (C)LPiece;
 */
JNIEXPORT jobject JNICALL Java_InterfaceAvecC_nativeInitPiece
  (JNIEnv *, jclass, jchar);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeInitHex
 * Signature: (IIC)LHex;
 */
JNIEXPORT jobject JNICALL Java_InterfaceAvecC_nativeInitHex
  (JNIEnv *, jclass, jint, jint, jchar);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeInitBoard
 * Signature: (ILjava/lang/String;)LBoard;
 */
JNIEXPORT jobject JNICALL Java_InterfaceAvecC_nativeInitBoard
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeInitGame
 * Signature: (Ljava/lang/String;LJeuHex;)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeInitGame
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcXCoord
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcXCoord
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcYCoord
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcYCoord
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeCalcPosition
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_nativeCalcPosition
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    nativePlacePiece
 * Signature: (IC)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_nativePlacePiece
  (JNIEnv *, jclass, jint, jchar);

/*
 * Class:     InterfaceAvecC
 * Method:    nativeGetSpots
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_InterfaceAvecC_nativeGetSpots
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
