/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceAvecC
 * Method:    isEmpty
 * Signature: (LCoordinates;)Z
 */
JNIEXPORT jboolean JNICALL Java_InterfaceAvecC_isEmpty
  (JNIEnv *, jclass, jobject);

/*
 * Class:     InterfaceAvecC
 * Method:    position
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_position
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
